name: cafeteria
description: Cafeteria online ordering

version: 0.1.0+1

environment:
  sdk: ">=1.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3

  provider: ^4.0.1
  google_fonts: ^0.2.0
  equatable: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/products/
  fonts:
    - family: LineIcons
      fonts:
        - asset: fonts/LineIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path: "assets/logo/cafeteria_logo.png"
